language: python

python:
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

env:
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  
script:
  - pytest